/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Integracion.continua.II;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
